
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: engineering_take_home_development
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: db
  port: 5432

test:
  <<: *default
  database: engineering_take_home_test
  username: <%= ENV.fetch("DB_USERNAME", "default_username") %> 
  password: <%= ENV.fetch("DB_PASSWORD", "default_password") %>  
  host: db
  port: 5432

production:
  <<: *default
  database: engineering_take_home_production
  username: engineering_take_home
  password: <%= ENV["ENGINEERING_TAKE_HOME_DATABASE_PASSWORD"] %>
